(#6) Text Editor component 구현
bbodek-development/bbodek-ui pull request #45
Opened 2023-11-23 08:21 UTC by Benj846

<img width="858" alt="image" src="https://github.com/bbodek-development/bbodek-ui/assets/38012605/3f37da95-d5ad-4d5c-8f71-bcbab2c13a94">

2023-11-26 09:27 UTC, shinYeongHyeon requested changes

2023-11-26 09:27 UTC, shinYeongHyeon commented on package.json
> +    "react-quill": "^2.0.0",
p1) 캐럿 제거 필요합니다

2023-11-26 14:46 UTC, Benj846 commented on package.json
> +    "react-quill": "^2.0.0",
- [ ] remove caret

2023-11-27 01:19 UTC, Benj846 commented
@shinYeongHyeon @cause38 @baegofda 
npm 배포를 위해, 일단 merge 하겠습니다, comment  있으시면 그래도 남겨주세요

2023-11-27 01:19 UTC, merged